### ISSUE TITLE
Create a POST API to fetch Personal Details/Educations Details in the backend

### ISSUE THREAD

**Issue by patilanurag** [Niche-538/UniGenie#43]
- [x] Fetch personal details/ educational details in the backend.
- [x] Create an appropriate DB table to store the same.
- [x] Create an API that returns appropriate values for every query made to that table.

**Comment by pratik-kamble** [comment]
![IMG_0506](https://user-images.githubusercontent.com/54627841/156687372-df3ebd0d-61c5-4a22-a154-9121a6b35b8c.jpeg)
![IMG_0507](https://user-images.githubusercontent.com/54627841/156687378-e9d63fad-1301-46eb-a818-c44645a896a7.jpeg)

**Comment by pratik-kamble** [comment]
![IMG_0508](https://user-images.githubusercontent.com/54627841/156687450-577b5610-0026-47f1-9e0a-4f56fa34a0c8.jpeg)

**Comment by pratik-kamble** [comment]
@patilanurag Please refer the screenshots to update
